export const TREE_SPECIES_SUGGESTIONS = [
	'Alder',
	'Ash',
	'Aspen',
	'Beech',
	'Birch',
	'Black Poplar',
	'Blackthorn',
	'Buckthorn',
	'Cherry',
	'Common Lime',
	'Crab Apple',
	'Elder',
	'Elm',
	'English Oak',
	'Field Maple',
	'Goat Willow',
	'Hawthorn',
	'Hazel',
	'Holly',
	'Hornbeam',
	'Horse Chestnut',
	'Larch',
	'Norway Maple',
	'Oak',
	'Pear',
	'Pedunculate Oak',
	'Plane',
	'Plum',
	'Poplar',
	'Rowan',
	'Silver Birch',
	'Small-leaved Lime',
	'Sweet Chestnut',
	'Sycamore',
	'Whitebeam',
	'Wild Cherry',
	'Willow',
	'Yew',
	'Acacia',
	'Apple',
	'Araucaria',
	'Atlas Cedar',
	'Bald Cypress',
	'Bay Laurel',
	'Box Elder',
	'Catalpa',
	'Cedar of Lebanon',
	'Chilean Pine',
	'Coast Redwood',
	'Cork Oak',
	'Copper Beech',
	'Dawn Redwood',
	'Dogwood',
	'Douglas Fir',
	'Downy Birch',
	'European Beech',
	'European Hornbeam',
	'False Acacia',
	'Fig',
	'Fringe Tree',
	'Giant Sequoia',
	'Ginkgo',
	'Golden Chain',
	'Grey Alder',
	'Grey Poplar',
	'Handkerchief Tree',
	'Italian Alder',
	'Italian Cypress',
	'Japanese Cherry',
	'Japanese Maple',
	'Judas Tree',
	'Kentucky Coffee Tree',
	'Korean Fir',
	'Laburnum',
	'Lawson Cypress',
	'Lime',
	'London Plane',
	'Magnolia',
	'Manna Ash',
	'Monkey Puzzle',
	'Mountain Ash',
	'Mulberry',
	'Norway Spruce',
	'Northern Red Oak',
	'Olive',
	'Oregon Grape',
	'Oriental Plane',
	'Paperbark Maple',
	'Persian Ironwood',
	'Pine',
	'Purple Leaf Plum',
	'Red Cedar',
	'Red Maple',
	'Red Oak',
	'Redbud',
	'Robinia',
	'Scotch Pine',
	'Serbian Spruce',
	'Service Tree',
	'Snowy Mespilus',
	'Spindle',
	'Spruce',
	'Stewartia',
	'Stone Pine',
	'Strawberry Tree',
	'Sugar Maple',
	'Swamp Cypress',
	'Sweet Gum',
	'Tamarisk',
	'Tulip Tree',
	'Turkish Hazel',
	'Weeping Willow',
	'Western Red Cedar',
	'White Mulberry',
	'White Poplar',
	'White Willow',
	'Wych Elm'
] as const;
